import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Leaderboard from '../../components/Leaderboard'

export default function App() {
    return (
        <>
            <Head>
                <title>Intro</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='paper container' style={{
                maxWidth:'100vw'
            }}>
                <Navbar />
                <Leaderboard />
            </main>

        </>
    )
}


