import Head from 'next/head'
import Game from '../../components/Game'

export default function App() {
    return (
        <>
            <Head>
                <title>Hangman</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Game />
            </main>
        </>
    )
}


