import Head from 'next/head'
import RegisterForm from '../components/RegisterForm'


export default function App() {
    return (
        <>
            <Head>
                <title>Intro</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='paper' style={{
                margin: '0',
                height: '100vh',
                overflow: 'hidden'
            }}>
                <RegisterForm/>
            </main>
        </>
    )
}


